### ISSUE TITLE
Placeholder problem

### ISSUE THREAD

**Issue by HenriqueKraemer** [sandrods/odf-report#69]
Sometimes the placeholders stop working without a specific reason, not replacing the variables. The template was build with Writer v4.4.2.2

The strange thing is that if I create a template from scratch going through the same placeholder, it works...

**Comment by sandrods** [comment]
It usually happens when you edit the placeholder inside OOficce/LOficce. 
Sometimes it messes up the styles and includes markup that prevents odf-report from identifying the placeholder.

The golden rule is: NEVER edit the placeholders. If you want to change one, delete it an write again, including the []

Hope that helps

**Comment by sandrods** [comment]
Yes, the golden rule is really applicable, **BUT** it´s about the **PLACEHOLDER**, not the whole template. If you have, say, `[USER]` in your template and you want to change to `[USERNAME]`, you should not edit and type `NAME`. 
Delete the PLACEHOLDER `[USER]` and type `[USERNAME]`.

HTH
